services:
  web:
    build: .
    container_name: grapelab_web
    volumes:
      - ./public:/app/public
    ports:
      - "8071:8080"
      - "8072:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
  
  db:
    image: postgres:17
    container_name: grapelab_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8073:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: